name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "pixel-positions"
          heroku_email: "rcrlourens@gmail.com"

      - name: Composer Update
        run: composer update

      - name: Deploy
        run: |
          composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader &&
          npm ci &&
          npm run build &&
          php artisan migrate --force &&
          php artisan optimize:clear &&
          php artisan config:cache &&
          php artisan route:cache
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
